console.log("working");
let hr1 = document.createElement("hr");
let dashboard = () => {
  let container = document.getElementById("showresult");
  container.innerHTML = null;
  let x = document.getElementById("dashboardicon");
  let y = document.querySelector("#dashboardicon>p");
  x.style.backgroundColor = "white";
  y.style.color = "black";
  let div = document.createElement("div");
  div.setAttribute("class", "dash-heading");
  let h = document.createElement("h1");
  h.innerText = "Dashboard";
  let p = document.createElement("p");
  p.innerText = "Last Update on 22-07-2022,8:35:08 AM";
  let input = document.createElement("div");
  input.setAttribute("class", "input-div");
  let inputbox1 = document.createElement("input");
  let inputbox2 = document.createElement("input");
  let p2 = document.createElement("p");
  p2.innerText = "Lead Prospected Date Range";
  inputbox1.type = "date";

  inputbox1.placeholder = "Start Date";
  inputbox2.type = "date";
  inputbox2.placeholder = "End Date";
  let div3 = document.createElement("div");
  div3.setAttribute("class", "dash-map");
  let h3 = document.createElement("h1");
  h3.innerText = "Leads";
  let div4 = document.createElement("div");
  let div5 = document.createElement("div");
  div5.setAttribute("class", "flex-div");
  let heading = document.createElement("h3");
  heading.innerText = "Top Location";
  let hr = document.createElement("hr");
  let img = document.createElement("img");
  img.src = "https://i.postimg.cc/TPRC65LM/world.png";
  div5.append(heading, hr, img);
  let div6 = document.createElement("div");
  div6.setAttribute("class", "side-div");
  let heading2 = document.createElement("h4");
  heading2.innerText = "Top Prospectors";
  let searchinput = document.createElement("input");
  searchinput.placeholder = "Search";
  let spam = document.createElement("span");
  spam.innerHTML = `<i class="fa-solid fa-magnifying-glass" style="color: gray"></i>`;
  let div7 = document.createElement("div");
  div7.innerHTML = `<h4>Name</h4> <h4>Capture</h4>`;
  div7.setAttribute("class", "text-gap");
  let checkbox = document.createElement("input");
  checkbox.setAttribute("type", "checkbox");
  checkbox.setAttribute("class", "checked1");
  let sign = document.createElement("h4");
  let div8 = document.createElement("div");
  div8.append(checkbox, sign);
  div8.setAttribute("class", "div-8");
  sign.innerText = "Unassigned";
  div6.append(heading2, spam, searchinput, hr, div7, div8);
  div4.setAttribute("class", "dash-grid");
  let hr1 = document.createElement("hr");
  let hr2 = document.createElement("hr");
  let hr3 = document.createElement("hr");
  let div9 = document.createElement("div");
  div9.setAttribute("class", "div-9");
  let h9 = document.createElement("h3");
  h9.innerText = "Top Industries";
  div9.append(h9, hr);
  let div10 = document.createElement("div");
  let h10 = document.createElement("h3");
  h10.innerText = "Top Company Sizes";
  div10.append(h10, hr1);
  div10.setAttribute("class", "div-10");

  //   start the next
  let div11 = document.createElement("div");
  div11.setAttribute("class", "div-11");
  let h11 = document.createElement("h3");
  h11.innerText = "Top Seniorities";
  div11.append(h11, hr2);
  let div12 = document.createElement("div");
  let h12 = document.createElement("h3");
  h12.innerText = "Top Titles";
  div12.append(h12, hr3);
  div12.setAttribute("class", "div-12");
  div4.append(div5, div6, div9, div10, div11, div12);

  div3.append(h3, div4);
  input.append(p2, inputbox1, inputbox2);
  div.append(h, p);
  container.append(div, input, div3);
};
// dashboard();

document.getElementById("dashboardicon").addEventListener("click", dashboard);
dashboard();
